# Dependencies
markdown:     redcarpet
highlighter:  rouge

# Setup
permalink:        pretty
source:           docs
title:            NineSevenThree
tagline:          "Simplified, responsive web design framework"
baseurl:          ""
exclude:          ["Makefile", "Gruntfile.js", "README.md", "LICENSE", "node_modules", "package.json"]

# Sass config
sass:
  sass_dir: ../
  style: compressed

# About/contact
author:
  name:           Resi Respati
  url:            https://twitter.com/resir014
  email:          resir014@gmail.com

# Custom vars
version:          0.5.1
github:
  repo:           https://github.com/veiraz/NineSevenThree.git
